#!/usr/bin/env python3
"""
Second-pass cleanup: take rows where the simple summariser bailed to
'See details' but the source clearly has a $ figure, and re-run them
through the strict summariser (which has explicit rules for tiers,
primary/supplementary, multi-paragraph stipends, etc.).

Inputs:
    deepseek_amount_summary_simple.csv  (from summarize_amounts.py --simple)
Outputs:
    deepseek_amount_summary_merged.csv  (simple + strict-recovered rows)
    deepseek_amount_recovered.csv        (just the rows that got upgraded)
    update_amount_display_merged.sql     (UPDATE SQL covering all rows)

The strict summariser has its own cache, so re-runs are free.
"""
from __future__ import annotations

import argparse
import csv
import sys
import time
from pathlib import Path

import amount_summarizer as strict_mod


def _sql_escape(s: str) -> str:
    return s.replace("'", "''")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1] if __doc__ else None)
    parser.add_argument(
        "--simple-csv",
        type=Path,
        default=Path("australia/usyd/deepseek_amount_summary_simple.csv"),
        help="Simple-prompt verdict CSV.",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Output directory (default: same dir as --simple-csv).",
    )
    args = parser.parse_args()

    if not args.simple_csv.exists():
        print(f"missing: {args.simple_csv}", file=sys.stderr)
        return 1

    out_dir = args.out_dir or args.simple_csv.parent
    out_dir.mkdir(parents=True, exist_ok=True)
    merged_csv = out_dir / "deepseek_amount_summary_merged.csv"
    recovered_csv = out_dir / "deepseek_amount_recovered.csv"
    sql_path = out_dir / "update_amount_display_merged.sql"

    with args.simple_csv.open() as f:
        rows = list(csv.DictReader(f))

    # Identify rows worth retrying: simple said "See details" but source has $.
    misses = [
        r for r in rows
        if r["summary"].strip().lower() == "see details"
        and "$" in (r.get("original") or "")
    ]
    print(f"loaded {len(rows)} rows; {len(misses)} candidates for strict retry")

    recovered: list[dict] = []
    still_bailed: list[dict] = []
    api_calls = 0
    cache_hits = 0

    for i, r in enumerate(misses, 1):
        source = r["original"]
        was_cached = strict_mod._read_cache(strict_mod._cache_key(source)) is not None
        verdict = strict_mod.summarize_amount(source)
        if was_cached:
            cache_hits += 1
        else:
            api_calls += 1
            time.sleep(0.1)

        new_summary = (verdict or {}).get("amount_display", "").strip() if verdict else ""
        if not new_summary or new_summary.lower() == "see details":
            still_bailed.append(r)
            print(f"  [{i:>3}/{len(misses)}] still See details  {r['title'][:55]}")
            continue

        recovered.append({
            "id": r["id"],
            "title": r["title"],
            "original": source,
            "simple_summary": r["summary"],
            "strict_summary": new_summary,
        })
        print(f"  [{i:>3}/{len(misses)}] RECOVERED  {new_summary:<40}  ← {r['title'][:50]}")

    # Build merged map: id → final summary (strict if recovered, else simple)
    recovered_by_id = {r["id"]: r["strict_summary"] for r in recovered}
    merged_rows: list[dict] = []
    for r in rows:
        final = recovered_by_id.get(r["id"], r["summary"])
        merged_rows.append({**r, "summary": final})

    with merged_csv.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(merged_rows[0].keys()))
        writer.writeheader()
        writer.writerows(merged_rows)

    if recovered:
        with recovered_csv.open("w", newline="") as f:
            writer = csv.DictWriter(
                f, fieldnames=["id", "title", "original", "simple_summary", "strict_summary"],
            )
            writer.writeheader()
            writer.writerows(recovered)

    # Build UPDATE SQL from the merged set (only rows where we have a non-empty
    # summary that differs from the original — no point updating to itself).
    sql_lines: list[str] = []
    for r in merged_rows:
        summary = (r.get("summary") or "").strip()
        if not summary:
            continue
        sql_lines.append(
            f"  ('{r['id']}'::uuid, "
            f"'{_sql_escape(summary)}', "
            f"'{_sql_escape(r['original'])}')"
        )
    if sql_lines:
        values_block = ",\n".join(sql_lines)
        sql = f"""-- Generated by retry_misses.py — merge of simple + strict-recovered rows.
-- Total: {len(merged_rows)} rows; {len(recovered)} recovered by strict retry.
-- Idempotent: WHERE clause requires amount_display = the original sentence.

with new_values(id, summary, original) as (
  values
{values_block}
)
update public.scholarships s
set
  amount_display = v.summary,
  description = case
    when s.description is null or btrim(s.description) = '' then v.original
    else s.description
  end
from new_values v
where s.id = v.id
  and s.amount_display = v.original;
"""
        sql_path.write_text(sql)

    print()
    print(f"Recovered:    {len(recovered)} / {len(misses)} retries")
    print(f"Still bailed: {len(still_bailed)}  (these are genuinely complex; hand-edit)")
    print(f"API calls:    {api_calls}  cache hits: {cache_hits}")
    print(f"Merged CSV:   {merged_csv}")
    if recovered:
        print(f"Recovered:    {recovered_csv}")
    if sql_lines:
        print(f"Update SQL:   {sql_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
